// const API='http://127.0.0.1:8000';let map,marker,circle,state={lat:28.6139,lon:77.209,place:'New Delhi',country:'India'};
// function init(){map=L.map('map',{zoomControl:false}).setView([state.lat,state.lon],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);marker=L.circleMarker([state.lat,state.lon],{radius:8,color:'#fff',weight:3,fillColor:'#16785b',fillOpacity:1}).addTo(map);circle=L.circle([state.lat,state.lon],{radius:500,color:'#26785f',weight:1,fillColor:'#26785f',fillOpacity:.08}).addTo(map);update();locate()}
// function update(){marker.setLatLng([state.lat,state.lon]);circle.setLatLng([state.lat,state.lon]);document.getElementById('coords').textContent=`${state.lat.toFixed(5)}, ${state.lon.toFixed(5)}`}
// async function locate(){if(!navigator.geolocation)return; navigator.geolocation.getCurrentPosition(async p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;update();map.setView([state.lat,state.lon],14);try{let r=await fetch(`${API}/api/location?lat=${state.lat}&lon=${state.lon}`),d=await r.json();state.place=d.city||'Current location';state.country=d.country||'';document.getElementById('place').textContent=state.place;document.getElementById('country').textContent=state.country}catch(e){}safety()},()=>{}, {enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
// async function safety(){try{let r=await fetch(API+'/api/safety',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat:state.lat,lon:state.lon})}),d=await r.json();document.getElementById('score').textContent=d.score;document.getElementById('meter').style.width=d.score+'%';document.getElementById('st').textContent=d.title;document.getElementById('msg').textContent=d.message}catch(e){}}
// function modal(title,body){document.getElementById('content').innerHTML=`<h3>${title}</h3>${body}`;document.getElementById('modal').classList.add('show')}
// document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('show');document.getElementById('locate').onclick=locate;document.getElementById('ml').onclick=()=>map.setView([state.lat,state.lon],15);document.getElementById('plus').onclick=()=>map.zoomIn();document.getElementById('minus').onclick=()=>map.zoomOut();
// document.getElementById('sos').onclick=async()=>{if(!confirm('Send an SOS alert with your current location?'))return;try{await fetch(API+'/api/sos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat:state.lat,lon:state.lon})});alert('SOS recorded. Production routing will send this to the configured helpdesk/authority.')}catch(e){alert('Backend unavailable. Please use your phone emergency call option.')}};
// document.getElementById('guide').onclick=()=>modal('AI Guide','<p>Ask about local safety, travel guidance, nearby services or your destination.</p><input id="q" placeholder="Ask something..." style="width:100%;padding:12px;border:1px solid #dce3df;border-radius:12px"><button class="action" id="ask">Ask Guide</button><div id="ans"></div>');
// document.getElementById('help').onclick=()=>modal('Nearby Help','<p>The production version can load verified police stations, hospitals, fire stations, washrooms and tourist landmarks around your live position.</p>');
// document.getElementById('report').onclick=()=>modal('Report an incident','<p>Send the current location as an incident so it can enter incident intelligence and area safety analysis.</p><button class="action" id="send">Report current location</button>');
// document.getElementById('trip').onclick=()=>modal('My Trip','<p>Trip details can include destination, planned duration, stay validity and required permits. These support contextual security and overstay checks.</p>');
// document.getElementById('modal').addEventListener('click',async e=>{if(e.target.id==='send'){await fetch(API+'/api/incident',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat:state.lat,lon:state.lon,type:'unsafe_situation'})});alert('Incident recorded.')}if(e.target.id==='ask'){let q=document.getElementById('q').value;let r=await fetch(API+'/api/guide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,lat:state.lat,lon:state.lon})});let d=await r.json();document.getElementById('ans').innerHTML=`<p><b>Guide:</b> ${d.answer}</p>`}});document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>{document.querySelectorAll('nav button').forEach(y=>y.classList.remove('active'));x.classList.add('active')});init();
